//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Audio_Player {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Audio_Player.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Byte[].
		/// </summary>
		internal static byte[] Comfortaa {
			get {
				object obj = ResourceManager.GetObject("Comfortaa", resourceCulture);
				return ((byte[])(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cross {
			get {
				object obj = ResourceManager.GetObject("cross", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap magnifying_glass {
			get {
				object obj = ResourceManager.GetObject("magnifying_glass", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap minimize {
			get {
				object obj = ResourceManager.GetObject("minimize", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap minimize_tray {
			get {
				object obj = ResourceManager.GetObject("minimize_tray", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap next {
			get {
				object obj = ResourceManager.GetObject("next", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap pause {
			get {
				object obj = ResourceManager.GetObject("pause", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap play {
			get {
				object obj = ResourceManager.GetObject("play", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap prev {
			get {
				object obj = ResourceManager.GetObject("prev", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap progress {
			get {
				object obj = ResourceManager.GetObject("progress", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap repeat {
			get {
				object obj = ResourceManager.GetObject("repeat", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap settings_small {
			get {
				object obj = ResourceManager.GetObject("settings_small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap shuffle {
			get {
				object obj = ResourceManager.GetObject("shuffle", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
		/// </summary>
		internal static System.Drawing.Icon simple {
			get {
				object obj = ResourceManager.GetObject("simple", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap simple_1 {
			get {
				object obj = ResourceManager.GetObject("simple_1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap stop {
			get {
				object obj = ResourceManager.GetObject("stop", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap toast_nope {
			get {
				object obj = ResourceManager.GetObject("toast_nope", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap toast_yup {
			get {
				object obj = ResourceManager.GetObject("toast_yup", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Byte[].
		/// </summary>
		internal static byte[] updater {
			get {
				object obj = ResourceManager.GetObject("updater", resourceCulture);
				return ((byte[])(obj));
			}
		}
	}
}
